### PR TITLE
Process type annotation while resolving dependencies

### LINKED ISSUE #101: Annotation that casts type is ommited
```
import com.softwaremill.macwire._
object Test{
  trait A
  trait B
  case class WireA(a:A)

  val a:A = new A with B
  val b:B = new A with B
  val res = wire[WireA]  
}
```
This beautiful piece of code fails with:

```
Error:(8, 27) Found multiple values of type [A$A69.this.A]: [List(get$$instance$$a, a, b)]
lazy val res:WireA = wire[WireA]
                         ^
```
because type annotaion on `b` is omitted while resolving dependencies.

### PR DESCRIPTION
**Pull request by mkljakubowski**
fixes #101

### CODE REVIEW

File: macros/src/main/scala/com/softwaremill/macwire/dependencyLookup/EligibleValuesFinder.scala [hunk 1]
```diff
@@ -78,8 +78,12 @@ private[dependencyLookup] class EligibleValuesFinder[C <: blackbox.Context](val
           doFind(tail, values.put(scope, Ident(name), body))
 
         case ValDefOrEmptyDefDef(name, tpt, rhs, symbol) if name.toString != "<init>" =>
-          // rhs might be empty for local def
-          doFind(tail, values.put(scope, Ident(name), treeToCheck(tree, rhs)))
+          if(tpt.tpe == rhs.tpe) {
```
Comment (adamw) [inline macros/src/main/scala/com/softwaremill/macwire/dependencyLookup/EligibleValuesFinder.scala]: Thanks for the PR! Maybe you could add a short comment here on why this check is needed (when the types are equal/distinct)?

Comment (mkljakubowski) [inline macros/src/main/scala/com/softwaremill/macwire/dependencyLookup/EligibleValuesFinder.scala]: comment added

**Comment by adamw** [comment]
2.2.4 released, should be in central soon. Thanks for the PR :)
